version: 2
updates:
  # Monitor npm dependencies (Node.js)
  - package-ecosystem: "npm"
    directory: "/script"        # Corrected path to package.json
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore(deps)"

  # Monitor Dockerfile base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
      - "security"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
